googleinterns/step173-2020

ubg/package-lock.json, ubg/src/Reviews/AllReviews.js, ubg/src/Reviews/NewReview.js, ubg/src/Reviews/Review.js, ubg/src/Reviews/Reviews.js, ubg/src/pages/Game.js
On each game page, users can leave a review and rating for the game. They appear from most to least recent. Users are required to leave a rating before submitting, but do not have to leave a text review. When a review is submitted, it is added to 'reviews' in AllReviews.js, and the contents of it are displayed.
The reviews are not persistent as they are not connected to Firebase yet.
=> Add basic comment/review function

.gitignore, package-lock.json, package.json, ubg/package-lock.json, ubg/package.json, ubg/src/App.js, ubg/src/pages/Game.js, ubg/src/pages/Room.js
Create a room in the game page and add users in the room page, you can add multiple users, later I'm going to use the user that's logged in.
=> Create game room and add users with join button

ubg/package-lock.json, ubg/package.json, ubg/src/Reviews/AllReviews.js, ubg/src/Reviews/NewReview.js, ubg/src/Reviews/Review.js, ubg/src/Reviews/Reviews.js
Styling was added with Material UI. 
Users can rate with the star system and optionally leave a text review.
=> Add styling to review section

ubg/package-lock.json, ubg/src/reviews/AllReviews.js, ubg/src/reviews/AllReviews.test.js, ubg/src/reviews/NewReview.test.js, ubg/src/reviews/Review.test.js, ubg/src/reviews/Reviews.test.js
Used wrong syntax for defining prop types in previous pr.
=> Fix prop type error for AllReviews

ubg/src/pages/Game.js, ubg/src/reviews/AllReviews.js
=> Add new icons on game page

ubg/src/pages/Search.js, ubg/src/search/AllFilters.js, ubg/src/search/DisplayGames.js
Move all filters and related components to a single file. Add 'Clear All Filter' button and 'Sort By' filter. Make search page pagination center in middle of the page.
=> Add 'Clear All Filter' button and 'Sort By' filter

ubg/src/reviews/AllReviews.js
Change initialize with useState()
=> Fix bug with reviews not loading on first load

ubg/src/App.js, ubg/src/common/Navbar.js, ubg/src/common/SearchField.js, ubg/src/pages/Search.js, ubg/src/search/AllFilters.js, ubg/src/search/DisplayGames.js
=> Search field

ubg/src/App.js, ubg/src/common/ProfileMenu.js, ubg/src/pages/Game.js, ubg/src/pages/Profile.js, ubg/src/reviews/AllReviews.js, ubg/src/reviews/Review.js
When signed in, users can add/delete a game to/from their favorites.
=> Implement favorite games for users

ubg/src/mafia/PersonalInfo.js, ubg/src/mafia/Player.js
PersonalInfo contains all the information you need to know about yourself.
Player is the card for "choose someone to kill"/"vote for someone to die".
=> add PeronalInfo and Player component to mafia

ubg/src/common/GameRoom.js, ubg/src/mafia/MafiaGame.js, ubg/src/mafia/MafiaNight.js, ubg/src/mafia/PersonalInfo.js, ubg/src/mafia/Player.js, ubg/src/pages/Room.js
Can't do anything now, but can display all the relavant data correctly.
=> Mafia night basic layout

ubg/src/mafia/MafiaNight.js, ubg/src/pages/Room.js
=> Mafia night with basic roles

ubg/src/mafia/MafiaDay.js, ubg/src/pages/Room.js
If all mafia dead or all townspeople dead, game ends.
=> Add in victory conditions

ubg/src/mafia/MafiaDay.js, ubg/src/mafia/MafiaGame.js, ubg/src/mafia/utils/AlertDialog.js
Fixed a bug so that pop-ups consistently work instead of only first time.
=> Use dialog alert for mafia day

ubg/src/mafia/MafiaDay.js, ubg/src/pages/Game.js, ubg/src/pages/Profile.js
Also simplified MafiaDay vote object
=> Enable create room for Mafia/Werewolf only

ubg/src/mafia/MafiaDay.js, ubg/src/mafia/MafiaNight.js, ubg/src/mafia/Player.js
=> Change player highlight, identify other mafias to mafia at night

ubg/src/common/Chat.js, ubg/src/mafia/MafiaDay.js, ubg/src/mafia/MafiaGame.js, ubg/src/mafia/MafiaNight.js, ubg/src/pages/Room.js
Fixed tie bugs and refresh voting bug during daytime
=> Move PersonalInfo and victory conditions to MafiaGame

ubg/src/common/GameRoom.js, ubg/src/common/WaitingRoom.js, ubg/src/mafia/EndModal.js, ubg/src/mafia/MafiaDay.js, ubg/src/mafia/MafiaGame.js, ubg/src/mafia/MafiaNight.js, ubg/src/pages/Room.js
When a game ends, players are redirected to the waiting room and shown results.
=> Allows for play again, fix joining game late bug, and shows players role at the end

ubg/src/common/Chat.js, ubg/src/common/Message.js, ubg/src/mafia/MafiaDay.js, ubg/src/mafia/MafiaNight.js, ubg/src/pages/Room.js
Also added day and night chat texts
=> Fix voting bug, move execution message, and italicize chat text from game

ubg/src/common/RulesDrawer.js, ubg/src/common/WaitingRoom.js, ubg/src/pages/Game.js
=> Display game description as innerHTML

ubg/src/mafia/MafiaGame.js, ubg/src/mafia/MafiaNight.js, ubg/src/mafia/Player.js, ubg/src/pages/Room.js
Chat should also delete itself at the start of each game
=> Change background at night and fix day/night chat bug

ubg/src/game/Implementation.js, ubg/src/pages/Game.js
=> Add game implementation section and go back button to game page

ubg/src/friend/FriendRequests.js, ubg/src/friend/Request.js, ubg/src/friend/UserResults.js, ubg/src/pages/Friends.js
=> Add functionality of accepting/declining friend requests

ubg/src/common/ProfileMenu.js, ubg/src/profile/AddFriendButton.js
Using a forEach loop for findUser() created issues for the useState hook, so that was modified with a normal for loop. A helper function called unfriend() was created to delete a user's id from a friends list.
=> Fix useState bug so profile page will accurately reflect friend status

ubg/src/pages/Profile.js, ubg/src/profile/Friend.js
=> Display friends on profile page

ubg/src/friend/ActivityFeed.js, ubg/src/friend/FriendRequests.js, ubg/src/pages/Game.js, ubg/src/pages/Home.js, ubg/src/reviews/AllReviews.js, ubg/src/reviews/NewReview.js, ubg/src/reviews/Reviews.js
Activity feed includes adding review and adding to favorite games.
=> Show user activity feed in homepage

ubg/src/friend/Request.js, ubg/src/game/CreateEventButton.js, ubg/src/pages/Game.js, ubg/src/profile/AddFriendButton.js
You can manually type in an email or select a user from your friends list.
=> Allow users to select friends when inviting to calendar event

ubg/src/game/CreateEventButton.js
=> Display email along with friend name in calendar invite
